# CASOINT_de_c_a_c++

https://github.com/aalvaroo7/CASOINT_de_c_a_c-.git

**En este codigo se ha corregido añadiendo la funcion main para que se pueda desarrollar el codigo y se han implementado dos gestiones de error, el código maneja específicamente excepciones de std::runtime_error durante la apertura del archivo y excepciones genéricas de std::exception durante la lectura del archivo. Además, incluye un bloque catch (...) para manejar cualquier otra excepción no prevista derivada de la expresión ... durante la lectura del archivo.**





